# XeLaTeX build policy / XeLaTeX 构建策略
$pdf_mode = 5;
$xelatex = 'xelatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$bibtex = 'bibtex %O %B';
$out_dir = 'build';
$aux_dir = 'build';
$max_repeat = 6;
